### ISSUE TITLE
l

### ISSUE THREAD

**Issue by candymanuu** [lausser/check_mysql_health#13]

**Comment by lausser** [comment]
Ah, ok, i thought there were problems at the very beginning, when the plugin connects to the database. As soon as i have some spare time, i will get a trial server and have a closer look. thanks for testing!

 

Gerhard

 

Von: candymanuu [mailto:notifications@github.com] 
Gesendet: Mittwoch, 14. Januar 2015 16:55
An: lausser/check_mysql_health
Betreff: [check_mysql_health] MS SQL 2000 -> database-online (#13)

 

Hi,

had a problem when using this plugin with mode = database-online for MS SQL 2000 server.
Problem is solved for me, but maybe somebody else has the same problem.


Solved it by changing this: 


[ ... ]
} elsif ($params{mode} =~ /server::database::online/) {
my @databaseresult = ();
if ($params{product} eq "MSSQL") {
if (DBD::MSSQL::Server::return_first_server()->version_is_minimum("9.x")) {
@databaseresult = $params{handle}->fetchall_array(q{
SELECT name, state, state_desc, collation_name FROM master.sys.databases
});
}
}
foreach (@databaseresult) {


[ ... ]


into this :


[ ... ]
} elsif ($params{mode} =~ /server::database::online/) {
my @databaseresult = ();
if ($params{product} eq "MSSQL") {
if (DBD::MSSQL::Server::return_first_server()->version_is_minimum("9.x")) {
@databaseresult = $params{handle}->fetchall_array(q{
SELECT name, state, state_desc, collation_name FROM master.sys.databases
});
} else {
@databaseresult = $params{handle}->fetchall_array(q{
SELECT name,
case 
when DATABASEPROPERTYEX(name,'Status')='ONLINE' then '0'
end as state,
DATABASEPROPERTYEX(name,'Status') as state_desc, DATABASEPROPERTYEX(name,'Collation') 
as collation_name
FROM master.dbo.sysdatabases
});
}
}
foreach (@databaseresult) {


[ ... ]


Best regards,
Bogdan
